# Generated by Django 5.1.7 on 2025-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('lokasi', models.CharField(max_length=255)),
                ('jenis_pelanggaran', models.CharField(max_length=255)),
                ('tindakan', models.TextField()),
            ],
        ),
    ]
