# Generated by Django 5.1.6 on 2025-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apd_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='lokasi',
            field=models.CharField(default='Lokasi Tidak Diketahui', max_length=255),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='tindakan',
            field=models.TextField(default='Peringatan'),
        ),
    ]
